import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Narbar from "./component/appbar";
import { Toaster } from "react-hot-toast";
import Provider from "./component/Provider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        <Narbar/>
        {children}
        <Toaster toastOptions={{style : {background : " rgb(51 65 85)",color : "#fff"}}}/>
        </Provider>
        </body>
    </html>
  );
}
